services:
  database:
    container_name: postgres-datmsc3
    image: postgres:latest
    ports:
    - 5435:5432
    volumes:
      - /Users/mac/Documents/DAT620MSC3set\data\postgres\datMSC3:/data/postgres
    env_file:
      datmsc3.env